#开发环境配置
server:
  #服务端口
  port: 9001
  socket:
    #总控采集各摆轮线SCADA数据的端口
    port: 10002
  servlet:
    # 项目contextPath
    context-path: /
    session:
      tracking-modes: cookie
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
#日志配置
logging:
  level:
    org.springframework: WARN
    org.spring.springboot.dao: debug
#用户配置
user:
  password:
    #密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5
#Spring配置
spring:
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  messages:
    #国际化资源文件路径
    basename: static/i18n/messages
    encoding: UTF-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  #文件上传
  servlet:
    multipart:
      max-file-size:  30MB
      max-request-size:  30MB
      enabled: true
      location: D:/profile/temp/
  devtools:
    restart:
      #热部署开关
      enabled: false
# PageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain:
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
# 项目相关配置
goldpeak:
  #名称
  name: Ginfon SCADA
  #版本
  version: 0.0.1
  #版权年份
  copyrightYear: 2020
  #文件上传路径
  upload: D:/profile/
  # 获取ip地址开关
  addressEnabled: false
  # 文件下载地址
  downloadPath: D:/profile/temp/
# SCADA配置
scada:
  socket:
    # 金峰云Socket配置
    cloud:
      # 是否开启云端推送
      enable: false
      server:
        # 金峰云Socket服务端配置
        host: 127.0.0.1
        # Socket服务端监听端口
        port: 8787
        # 断线重连频率
        reconnect:
          time: 10
    # 本地Socket服务端配置 待整合后废弃
    server:
      # WCS服务端地址
      host: 127.0.0.1
      # WCS服务端端口
      port: 2723
      # 重连时间间隔（S）
      reconnect:
        time: 10
      # 设备别名
      alias: SHSF_01
      plcport1: 12001
      plcport2: 12002
      plcport3: 12003
    #顺丰服务器的配置
    sfServer:
      ip: 127.0.0.1
      port: 3000
      heartbeat: 4000
      reconnect: 600000
      #总控的编号
      manageLineNo: ZK-JFWL
      #分控的线体编号，以;分割
      lineNo: JFWL-01;JFWL-02;JFWL-03;JFWL-04
      supplier: JFWL;JFWL;JFWL;JFWL
# 定时器
quartz:
  schedule:
    speed: 0 0/1 * * * ?
    cloud: 0/15 * * * * ?
socket: 
  name: WCS;YUN
  ip: 127.0.0.1;127.0.0.1
  port: 2723;8011

linedevice:
  lineip: CA,12.168.21.51;ZA,12.168.21.52;ZB,12.168.21.53;ZC,12.168.21.54;GB,12.168.21.55;FB,12.168.21.56;FC,12.168.21.57;FD,12.168.21.58
